name: check next race date
on: 
  workflow_dispatch:
# on:
#  schedule:
#   - cron: "0 5 * * MON"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://ergast.com/api/f1/current/next.json
          save-location: next_race_date
      - id: get_json
        run: |
              content=`cat ./next_race_date/data.json`
              # the following lines are only required for multi line json
              content="${content//'%'/'%25'}"
              content="${content//$'\n'/'%0A'}"
              content="${content//$'\r'/'%0D'}"
              # end of optional handling for multi line json
              echo "{NEXT-DATE-JSON}={$content}" >> "$GITHUB_ENV"
              # echo "::set-output name=nextDate::$content"
      - name: Get next race date
        id: get_date
        run: |
          date="${{fromJson(steps.get_json.outputs.nextDate).MRData.RaceTable.Races[0].date}}"
          # time="${{fromJson(steps.get_json.outputs.nextDate).MRData.RaceTable.Races[0].time}}"
          echo "{$date}"
          echo "{NEXT-DATE}={$date}" >> "$GITHUB_ENV"
          # echo "::set-output name=nextDate::$date"
      - name: Get current date
        id: current_date
        run: |
          echo "{$(date +'%Y-%m-%d')}"
          echo "{CURRENT-DATE}={$(date +'%Y-%m-%d')}" >> "$GITHUB_ENV"
          # echo "::set-output name=currentDate::$(date +'%Y-%m-%d')"
      - name: Build project
        if: ${{ steps.current_date.outputs.currentDate <  steps.current_date.outputs.nextDate}}
        run:  |
              echo "TODAVIA NO ES EL DIA"
      
