name: check next race date
on: 
  workflow_dispatch:
# on:
#  schedule:
#   - cron: "0 5 * * MON"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://ergast.com/api/f1/current/next.json
          save-location: next_race_date.json
