name: check next race date
on: 
  workflow_dispatch:
# on:
#  schedule:
#   - cron: "0 5 * * MON"
jobs:
  check_date:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch API Data 📦
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://ergast.com/api/f1/current/next.json
          save-location: next_race_date
      - id: get_json
        run: |
              content=`cat ./next_race_date/data.json`
              # the following lines are only required for multi line json
              content="${content//'%'/'%25'}"
              content="${content//$'\n'/'%0A'}"
              content="${content//$'\r'/'%0D'}"
              # end of optional handling for multi line json
              echo "next_date_json=$content" >> "$GITHUB_OUTPUT"
      - name: Get next race date
        id: get_date
        run: |
          date="${{fromJson(steps.get_json.outputs.next_date_json).MRData.RaceTable.Races[0].date}}"
          time="${{fromJson(steps.get_json.outputs.next_date_json).MRData.RaceTable.Races[0].time}}"
          composed="$date $time"
          fulltime=`date -d "$composed" '+%s%3N'`
          echo "$fulltime"
          echo "next_date=$fulltime" >> "$GITHUB_OUTPUT"
      - name: Get current date
        id: current_date
        run: |
          date=`date -d '-6 hour' '+%s%3N'`
          echo "$date"
          echo "current_date=$date" >> "$GITHUB_OUTPUT"
    outputs:
      next_date: ${{ steps.get_date.outputs.next_date }}
      current_date: ${{ steps.current_date.outputs.current_date }}
      
    
      
  deploy_to_vercel:
    needs: check_date
    if: ${{ needs.check_date.outputs.current_date < needs.check_date.outputs.next_date }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
            
