name: Deploy on mondays if round has finished
# on:
#   workflow_dispatch:
on:
  schedule:
    - cron: "00 04 * * MON"
jobs:
  deploy_to_vercel:
    needs: check_date
    # if: ${{ needs.check_date.outputs.current_date < needs.check_date.outputs.last_date }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
